# Generated by Django 2.1.3 on 2018-11-22 14:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alternative_response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(max_length=400)),
                ('date_created', models.DateTimeField()),
                ('date_updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_key', models.CharField(max_length=50)),
                ('default_response', models.CharField(max_length=400)),
                ('date_created', models.DateTimeField()),
                ('date_updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='response_hook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(max_length=50)),
                ('action_type', models.CharField(choices=[('rest', 'Rest Call'), ('rpc', 'Procedure Call'), ('txt', 'Text Response')], default='rest', max_length=20)),
                ('response', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField()),
                ('date_updated', models.DateTimeField()),
                ('status', models.CharField(choices=[('A', 'Active'), ('P', 'Passive')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(default=uuid.uuid4, editable=False, max_length=32)),
                ('parameter_key', models.CharField(max_length=30)),
                ('parameter_value', models.CharField(max_length=30)),
                ('intent_group', models.CharField(max_length=30)),
                ('date_created', models.DateTimeField()),
                ('date_dismissed', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=14)),
                ('crm_ref', models.CharField(max_length=13)),
                ('agent_ref', models.CharField(max_length=13)),
                ('date_created', models.DateTimeField()),
                ('date_last_login', models.DateTimeField()),
                ('date_updated', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot.user'),
        ),
        migrations.AddField(
            model_name='alternative_response',
            name='response_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot.response'),
        ),
    ]
