# Generated by Django 2.1.3 on 2018-12-21 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='intent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent_name', models.CharField(max_length=30)),
                ('date_created', models.DateTimeField()),
                ('date_dismissed', models.DateTimeField()),
                ('status', models.CharField(choices=[('A', 'Active'), ('P', 'Passive')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='intent_parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_key', models.CharField(max_length=30)),
                ('parameter_value', models.CharField(max_length=30)),
                ('life_span', models.IntegerField()),
                ('expire_date', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('P', 'Passive')], default='A', max_length=1)),
                ('intent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot.intent')),
            ],
        ),
        migrations.RenameField(
            model_name='session',
            old_name='intent_group',
            new_name='active_intent',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='alternative_response',
            name='response_id',
        ),
        migrations.RemoveField(
            model_name='session',
            name='parameter_key',
        ),
        migrations.RemoveField(
            model_name='session',
            name='parameter_value',
        ),
        migrations.AddField(
            model_name='intent',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot.session'),
        ),
    ]
