# Generated by Django 2.1.3 on 2018-12-21 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_auto_20181221_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='session',
            new_name='session_id',
        ),
    ]
