# Generated by Django 2.1.3 on 2018-12-25 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_auto_20181221_1615'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='session',
            new_name='chat_session',
        ),
    ]
