# Generated by Django 2.1.3 on 2018-12-25 21:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_auto_20181225_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_session',
            name='session_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36),
        ),
    ]
