# Generated by Django 2.1.3 on 2018-12-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_auto_20181225_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_session',
            name='active_intent',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
