# Generated by Django 2.1.3 on 2018-12-25 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_auto_20181225_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_session',
            name='date_dismissed',
            field=models.DateTimeField(null=True),
        ),
    ]
