# Generated by Django 2.1.3 on 2018-12-25 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_auto_20181225_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intent',
            name='date_dismissed',
            field=models.DateTimeField(null=True),
        ),
    ]
