# Generated by Django 2.1.3 on 2018-12-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_auto_20181225_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intent_parameter',
            name='parameter_value',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
