#!/bin/sh

until PGPASSWORD=postgres psql --host postgresql --username postgres -c '\l' > /dev/null; do
  echo "Postgres is unavailable - sleeping"
  sleep 1
done
echo "Connected Postgres - running"

apt-get update
# apt-get install -y git vim build-essential python3.5-dev python3-venv \
#   libncurses5-dev fabric postgresql-9.5 postgresql-server-dev-9.5 \
#   libjpeg62-dev zlib1g-dev libfreetype6-dev

PGPASSWORD=postgres psql --host postgresql --username postgres -f ./db-data/covo.sql


export PYTHONUNBUFFERED=0
#pip3 install djangorestframework==3.9.0
python3 ./chatbot/manage.py migrate
python3 ./chatbot/manage.py runserver 0.0.0.0:8092
